name: ant
description: ANT — AI Tools Directory App with auto-update
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.7
  http: ^0.13.5
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
  animate_do: ^2.0.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
